// -------------- Generated by Tangsem.Tooling.CodeGen.ApiClient.ApiMethodGen.ApiClientCode() -----------

using CostTracker.Domain.Core;
using CostTracker.Domain.Core.DTOs;

namespace CostTracker.ApiClient;

using System.Net.Http;
using System.Web;
using Tangsem.WebApiClient.Extensions;

/// <summary>
/// Generated part of CostTrackerApiClient class.
/// </summary>
public partial class CostTrackerApiClient
{
  private readonly HttpClient _hc;

  public CostTrackerApiClient(HttpClient hc)
  {
    this._hc = hc;
  }

  /// <summary>
  /// GetWeatherForecast Async.
  /// </summary>
  public async Task<WeatherForecast[]> GetWeatherForecast_Async()
  {
    var url = $"/weatherforecast";


    return await this._hc.GetAsJson_Async<WeatherForecast[]>(url);
  }
}